export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const LOGIN = 'LOGIN'
export const SIGNUP = 'SIGNUP'
export const CHECK_LOGIN_STATUS = 'STATUS'
export const Error_API='ERROR'
export const LOADING = 'LOADING'